config/routes.rb
Rails.application.routes.draw do
  
  get 'intro' => 'intro#index'

  root 'cities#index'

  get 'cities/fighterslist' => 'cities#fighters_list'
  get 'cities/fight/:enemy_id' => 'cities#fight'
  resources :cities

  get 'buildings' => 'buildings#index'
  post 'buildings' => 'buildings#create'
  delete 'buildings/:id' => 'buildings#destroy'
  get 'buildings/collect/:id' => 'buildings#collect'

  get 'units' => 'units#index'
  post 'units' => 'units#create'
  delete 'units/:id' => 'units#destroy'

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :buildings
  has_many :units
  validates :city_hash, uniqueness: true, presence: true
  validates_length_of :name, :minimum => 1, :maximum => 25, :allow_blank => false
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city #, only: [:show, :edit, :update, :destroy, :fighters_list]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.select(:id, :name, :locked, :stone, :wood, :win, :lose, :population).order(population: :desc).limit(30)
    @city_hash = cookies[:city_hash]
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    redirect_to_default_page_if_no_city("First create the ship")
  end

  # GET /cities/new
  def new
    if(@city.blank?)
      @city = City.new
    else
      respond_to do |format|
        format.html { redirect_to city_url(@city), notice: "" }
        format.json { head :no_content }
      end
    end

  end

  # GET /cities/1/edit
  def edit
    redirect_to_default_page_if_no_city ("Can't find your ship")
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)
    @city.city_hash = generate_unique_hash
    cookies[:city_hash] = @city.city_hash
    cookies[:city_hash] = { :value => @city.city_hash, :expires => 168.hour.from_now }

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /cities/fighterslist/
  def fighters_list
    # @cities = City.select(:id,:name).sample(20)
    @cities = City.select(:id,:name, :population).where().not(id: @city.id).limit(20).order("RANDOM()")
    # @cities(@city.id)
    render json: @cities, status: :ok
  end

  # GET /cities/fight/:eneny_id
  def fight
    if(@city.blank?)
      render json: {error: "Can't find correct data!"}, status: :unprocessable_entity and return
    elsif(@city.last_fight_date > 3.minutes.ago)
      left_minute =  Time.at((@city.last_fight_date + 3*60 - Time.now)).utc.strftime("%M:%S") #=> "00:00"
      render json: {error: "You are not recovered from previous fight. "+left_minute+" left until recovery!"}, status: :unprocessable_entity and return
    end

    @enemyCity = City.find(params[:enemy_id])
    if @enemyCity.blank?
      render json: {error: "Can't find current enemy!"}, status: :unprocessable_entity and return
    end

    myAttack,myDefence = @city.units.sum(:attack, :defence)
    enemyAttack = @enemyCity.units.sum(:attack)

    winPopulationChange = rand(100..150)
    losePopulationChange = rand(40..60)
    populationChange = 0

    if myAttack > enemyAttack
      notice = "You won"
      @city.last_fight_date = Time.now
      # change stat
      @city.win = @city.win + 1
      @enemyCity.lose = @enemyCity.lose + 1
      # change buildings
      damageCity @enemyCity
      # delete units
      #@enemyCity.units.delete_all #lost player will not know about his lost. Have to add later when player can see history
      # add experience
      @city.population = @city.population + winPopulationChange
      @enemyCity.population = @enemyCity.population + losePopulationChange
      populationChange = winPopulationChange
    else
      notice = "You lost"
      # change stat
      @city.lose = @city.lose + 1
      @enemyCity.win = @enemyCity.win + 1
      # change stat
      damageCity @city
      # delete units
      @city.units.delete_all
      # add experience
      @city.population = @city.population + losePopulationChange
      @enemyCity.population = @enemyCity.population + winPopulationChange
      populationChange = losePopulationChange
    end

    City.transaction do
      if @city.save! && @enemyCity.save!
        render json: {notice: notice, population: populationChange}, status: :ok and return
      else
        render json: {error: "Fight cancellad"}, status: :unprocessable_entity
        raise ActiveRecord::Rollback
      end
    end

  end


  # DELETE /cities/1
  # DELETE /cities/1.json
  # def destroy
  #
  #   if(!@city)
  #     notice = 'City is already deleted.'
  #   else
  #     notice = 'City was successfully destroyed.'
  #     @city.destroy
  #     cookies.delete(:city_hash)
  #   end
  #
  #   respond_to do |format|
  #     format.html { redirect_to cities_url, notice: notice }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      # @city = City.find(params[:id])
      hash = cookies[:city_hash]
      @city = City.find_by(city_hash: hash)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:name, :locked, :city_type)
    end

    def generate_unique_hash
      enum = [*'a'..'z', *'A'..'Z', *0..9].shuffle.permutation(15)
      enum.next.join
    end

    # redirect to no city page
    def redirect_to_default_page_if_no_city(note)
      if(@city.blank?)
        respond_to do |format|
          format.html { redirect_to new_city_url, notice: note }
          format.json { head :no_content }
        end
      end
    end

    def damageCity city
      buildings = city.buildings.offset(3)
      buildings.each { |b| b.destroy }
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading text-center">
        <h1>Give a name to your Star Destroyer</h1>
      </div>
      <div class="panel-body">
        <%= form_for(@city) do |f| %>
            <% if @city.errors.any? %>
                <div id="error_explanation">
                  <!--<h2><%= pluralize(@city.errors.count, "error") %> prohibited this ship from being saved:</h2>-->

                  <ul>
                    <% @city.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="form-group">
              <div class="field">
                <%= f.text_field :name, class: "input-lg inputlg col-xs-12 col-md-12" %>
              </div>
            </div>
            

            <br/> <br/> <br/>
            <div class="form-group">
              <div class="field">
                <%= f.submit "Save", :class => 'btn btn-success btn-lg col-xs-4 col-md-4 col-xs-offset-4 .col-md-offset-4' %>
              </div>
            </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/cities/edit.html.erb
<%= render 'form' %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>


<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading text-center">
        <h1>Leaderboard (Best <%= @cities.count %>)</h1>
      </div>
      <div class="panel-body">
        <table class="table table-condensed table-striped">
          <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>XP</th>
            <th>Win</th>
            <th>Lose</th>
            <th>Minerals</th>
            <th>Energy</th>
          </tr>
          </thead>

          <tbody>
          <% @cities.each_with_index do |city,index| %>
              <tr>
                <td><%= index+1 %>.</td>
                <td><%= city.name %></td>
                <td><%= city.population %></td>
                <td><%= city.win %></td>
                <td><%= city.lose%></td>
                <td><%= city.stone %></td>
                <td><%= city.wood %></td>
              </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/cities/new.html.erb
<%= render 'form' %>

app/views/cities/show.html.erb
<div ng-app="cityModule" ng-cloak
     ng-init="city.stone=<%= @city.stone %>;city.wood=<%= @city.wood %>;city.max_building_amount=<%= @city.max_building_amount %>;city.max_army_amount=<%= @city.max_army_amount %>;city.lose=<%= @city.lose %>;city.win=<%= @city.win %>;city.population=<%= @city.population %>">

  <div ng-controller="cityController">
    <div class="row">
      <div class="col-xs-9 col-md-9">
        <div class="panel panel-default panel-transparent">
          <div class="panel-body">

            <p id="notice"><%= notice %></p>

            <!--Stats panel-->
            <div class="container-fluid">
              <!--Ship image-->
              <div class="col-xs-4 col-md-4">
                <div id="myShip"></div>
              </div>
              <!--Stats panel-->
              <div class="col-xs-8 col-md-8">
                <div class="row">
                  <div class="col-xs-3">
                    <strong>Ship Name:</strong>

                    <p><%= @city.name %> (<%= link_to 'change', edit_city_path(@city) %>)</p>
                  </div>
                  <div class="col-xs-3">
                    <strong>XP</strong>

                    <p>{{city.population}}</p>
                  </div>
                  <div class="col-xs-3">
                    <strong>Minerals</strong>

                    <p>{{city.stone}}</p>
                  </div>
                  <div class="col-xs-3">
                    <strong>Energy</strong>

                    <p>{{city.wood}}</p>
                  </div>
                </div>
                <div class="row">
                  <div class="col-xs-3">
                    <!-- Fight button -->
                    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#fightModal" ng-click="GetAllFighterCities()">
                      Battle
                    </button>
                  </div>
                  <div class="col-xs-3">
                  </div>
                  <div class="col-xs-3">
                    <strong>Win</strong>

                    <p>{{city.win}}</p>
                  </div>
                  <div class="col-xs-3">
                    <strong>Lose</strong>

                    <p>{{city.lose}}</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Modal Fighter List-->
        <div class="modal fade" id="fightModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content  panel-danger">
              <div class="modal-header panel-danger">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Fight with enemies</h4>
              </div>
              <div class="modal-body">

                <ul class="list-group">

                  <div data-ng-repeat="cityObj in fighterCities">
                    <li class="list-group-item">

                        <span class="btn-group">
                        <button type="button" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#fightResultModal" ng-click="FightWithCity(cityObj)">Attack</button>
                      </span>
                      {{cityObj.name}} (XP:{{cityObj.population}})
                    </li>
                  </div>
                </ul>

              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <!--<button type="button" class="btn btn-primary">Save changes</button>-->
              </div>
            </div>
          </div>
        </div>

        <!-- Modal Fighter Result-->
        <div class="modal fade" id="fightResultModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" ng-click="CloseAllModals()">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Fight Result</h4>
              </div>
              <div class="modal-body">
                <div id="fight_result">
                  <div id="fight_result_notice" class="text-center" ng-hide="fightResult.error">
                    {{fightResult.notice}}
                  </div>
                  <div id="fight_result_population" class="text-center" ng-hide="fightResult.error">
                    Gained XP: {{fightResult.population}}
                  </div>
                  <div id="fight_result_population" class="text-center" ng-show="fightResult.error">
                    {{fightResult.error}}
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal" ng-click="CloseAllModals()">Close</button>
                <!--<button type="button" class="btn btn-primary">Save changes</button>-->
              </div>
            </div>
          </div>
        </div>

        <!--Building and Units panels-->
        <div class="row">
          <div id="exTab3" class="container-fluid">
            <div>
              <!--Panel Selection/Menu buttons-->
              <ul class="nav nav-pills">
                <li class="active">
                  <a href="#1b" data-toggle="tab">
                    Buildings
                    ({{buildings.length}}/{{city.max_building_amount}})
                  </a>
                </li>
                <li><a href="#2b" data-toggle="tab">
                  Starfighters
                  ({{units.length}}/{{city.max_army_amount}})
                </a>
                </li>
              </ul>
              <!--Panel contens-->
              <div class="tab-content clearfix">
                <!--buildings panel-->
                <div class="tab-pane fade in active" id="1b">

                  <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#buildingModal">
                    <span class="glyphicon glyphicon-plus-sign"></span> Build
                  </button>

                  <hr/>

                  <div data-ng-repeat="building in buildings" style="float: left;">
                    <div id="building_item_{{building.resource_type}}">
                      <!--{{building}}-->
                      <p ng-show="building.resource_type==1">Mineral Sucker</p>

                      <p ng-show="building.resource_type==2">Energy Generator</p>

                      <button type="button" class="btn btn-sm btn-success" ng-click="Collect(building)">Collect</button>
                      <button type="button" class="btn btn-sm btn-danger" ng-click="DeleteBuilding(building)">Delete</button>
                    </div>
                  </div>

                </div>
                <!--units panel-->
                <div class="tab-pane fade" id="2b">

                  <button type="button" class="btn btn-success btn-lg" data-toggle="modal" data-target="#unitModal">
                    <span class="glyphicon glyphicon-plus-sign"></span> Build
                  </button>

                  <hr/>

                  <div data-ng-repeat="unit in units" style="float: left;">
                    <div>
                      <!--{{unit}}-->

                      <div id="unit_item_{{unit.unit_type}}">
                        <div>
                          <p ng-show="unit.unit_type==1">Gunbolt-2</p>

                          <p ng-show="unit.unit_type==2">TIE Fire</p>

                          <p ng-show="unit.unit_type==3">X-TIE Fighter</p>

                          <p ng-show="unit.unit_type==4">T65XJ5</p>
                        </div>
                        <div>Attack: {{unit.attack}}</div>
                        <div>Defense: {{unit.defence}}</div>
                      </div>
                      <div class="unit-delete-button">
                        <button type="button" class="btn btn-lg btn-danger" ng-click="DeleteUnit(unit)">Destroy</button>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>

        </div>

        <!--building templates panel-->
        <div class="modal fade" id="buildingModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog modal-dialog-center" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Buildings</h4>
              </div>
              <div class="modal-body">
                <div class="row">
                  <div class="col-xs-6 col-md-6">
                    <div>
                      <p>Mineral Sucker</p>
                      <%= image_tag("Energy_Generator.jpg") %>
                    </div>
                    <button type="button" class="btn btn-lg btn-success" ng-click="CreateBuilding(1)">
                      Buy (-20,-20)
                    </button>
                  </div>
                  <div class="col-xs-6 col-md-6">
                    <div>
                      <p>Energy Generator</p>
                      <%= image_tag("Minera_Sucker.jpg") %>
                    </div>

                    <button type="button" class="btn btn-lg btn-success" ng-click="CreateBuilding(2)">
                      Buy (-20,-20)
                    </button>
                  </div>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <!--<button type="button" class="btn btn-primary">Save changes</button>-->
              </div>
            </div>
          </div>
        </div>
        <!--units template panel-->
        <div class="modal fade" id="unitModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog modal-dialog-center" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Buildings</h4>
              </div>
              <div class="modal-body">
                <div class="row">
                  <div class="col-xs-3 col-md-3">
                    <div>
                      <p>Gunbolt-2</p>
                      <%= image_tag("gunboat_2_small.jpg") %>
                    </div>
                    <button type="button" class="btn btn-sm btn-success" ng-click="CreateUnit(1)">Buy (-100,-100)
                    </button>
                  </div>

                  <div class="col-xs-3 col-md-3">
                    <div>
                      <p>TIE Fire</p>
                      <%= image_tag("TIE_Fire_Control_small.jpg") %>
                    </div>
                    <button type="button" class="btn btn-sm btn-success" ng-click="CreateUnit(2)">Buy (-150,-150)
                    </button>
                  </div>
                  <div class="col-xs-3 col-md-3">
                    <div>
                      <p>X-TIE Fighter</p>
                      <%= image_tag("X-TIE-Fighter_small.jpg") %>
                    </div>
                    <button type="button" class="btn btn-sm btn-success" ng-click="CreateUnit(3)">Buy (-300,-500)
                    </button>
                  </div>
                  <div class="col-xs-3 col-md-3">
                    <div>
                      <p>T65XJ5</p>
                      <%= image_tag("T65XJ5_Stealth_small.jpg") %>
                    </div>
                    <button type="button" class="btn btn-sm btn-success" ng-click="CreateUnit(4)">Buy (-1000,-800)
                    </button>
                  </div>


                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <!--<button type="button" class="btn btn-primary">Save changes</button>-->
              </div>
            </div>
          </div>
        </div>

      </div>

      <!--Battle panel-->
      <div class="col-xs-3 col-md-3">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Battle History</h3>
          </div>
          <div class="panel-body">
            Coming soon
          </div>
        </div>
      </div>
    </div>

  </div>
</div>